version: "2.1"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      IS_DOCKER: "true"
      ENCRYPT_PASS_PHRASE: aa
    command: yarn run dev
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app
