name: CI

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: NPM Publish
      run: |
        CI_COMMIT_TAG=${GITHUB_REF##*/}
        npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
        sed -ie s/'"version".*"'/'"version":"'$CI_COMMIT_TAG'"'/g ./package.json
        yarn build
        yarn publish --new-version $CI_COMMIT_TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
